#!/usr/bin/env python3
"""PreCompact hook — captures session state before context compaction.

Fires before auto or manual /compact. Writes two files:
  - memory/compaction-handoff.md  (read by session-start.sh post-compaction)
  - Updates ## Active Session section in memory/MEMORY.md

Input (stdin): JSON with session_id, transcript_path, cwd, trigger
Output: none (PreCompact stdout is not injected into Claude's context)
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone


def run(cmd: list[str], cwd: str | None = None) -> str:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=10,
            cwd=cwd,
        )
        return result.stdout.strip()
    except Exception:
        return ""


def memory_dir_for(cwd: str) -> str:
    """Compute the auto-memory directory path from the project cwd.

    Claude stores auto-memory at:
      ~/.claude/projects/<slug>/memory/
    where <slug> is the absolute cwd with every non-alphanumeric character
    (slashes, underscores, dots, etc.) replaced by '-'.
    """
    slug = re.sub(r"[^a-zA-Z0-9-]", "-", cwd)
    return os.path.expanduser(f"~/.claude/projects/{slug}/memory")


def extract_agent_ids(transcript_path: str, lookback: int = 200) -> list[str]:
    """Parse the last N lines of the session JSONL for running task IDs."""
    task_ids: list[str] = []
    try:
        with open(transcript_path, encoding="utf-8") as f:
            lines = f.readlines()
        recent = lines[-lookback:] if len(lines) > lookback else lines
        seen: set[str] = set()
        completed: set[str] = set()
        for line in recent:
            try:
                ev = json.loads(line)
                # task-notification events carry task-id and status
                msg = ev.get("message", {})
                content = msg.get("content", [])
                if isinstance(content, list):
                    for block in content:
                        if isinstance(block, dict) and block.get("type") == "tool_result":
                            pass
                # Check for task notification in user messages (system-injected)
                if ev.get("type") == "user":
                    raw = json.dumps(ev)
                    ids = re.findall(r'<task-id>([^<]+)</task-id>', raw)
                    statuses = re.findall(r'<status>([^<]+)</status>', raw)
                    for tid, status in zip(ids, statuses):
                        seen.add(tid)
                        if status in ("completed", "failed", "stopped"):
                            completed.add(tid)
            except (json.JSONDecodeError, KeyError):
                continue
        task_ids = [t for t in seen if t not in completed]
    except Exception:
        pass
    return task_ids


def capture_git_state(cwd: str) -> dict[str, str]:
    branch = run(["git", "branch", "--show-current"], cwd=cwd)
    status = run(["git", "status", "--short"], cwd=cwd)
    log = run(["git", "log", "--oneline", "-3"], cwd=cwd)
    return {"branch": branch, "status": status or "(clean)", "log": log}


def capture_pr_context(cwd: str, branch: str) -> dict[str, str] | None:
    if not branch or branch == "main":
        return None
    out = run(
        ["gh", "pr", "view", "--json", "number,url,title,headRefName"],
        cwd=cwd,
    )
    if not out:
        return None
    try:
        pr = json.loads(out)
        return {
            "number": str(pr.get("number", "")),
            "url": pr.get("url", ""),
            "title": pr.get("title", ""),
        }
    except Exception:
        return None


def write_handoff(memory_dir: str, data: dict) -> None:
    os.makedirs(memory_dir, exist_ok=True)
    path = os.path.join(memory_dir, "compaction-handoff.md")
    ts = data["timestamp"]
    git = data["git"]
    pr = data.get("pr")
    agent_ids = data.get("agent_ids", [])
    trigger = data.get("trigger", "auto")

    lines = [
        "<!-- auto-generated by precompact.py — do not edit manually -->",
        f"# Compaction Handoff — {ts}",
        "",
        f"**Trigger:** {trigger}",
        f"**Session:** {data.get('session_id', '?')}",
        "",
        "## Git State",
        f"- **Branch:** `{git['branch']}`",
        f"- **Status:** {git['status']}",
        "- **Recent commits:**",
    ]
    for commit_line in git["log"].splitlines():
        lines.append(f"  - {commit_line}")

    if pr:
        lines += [
            "",
            "## Active PR",
            f"- **PR #{pr['number']}:** {pr['title']}",
            f"- **URL:** {pr['url']}",
        ]

    if agent_ids:
        lines += [
            "",
            "## Background Agents (still running at compaction)",
        ]
        for tid in agent_ids:
            lines.append(f"- `{tid}`")
    else:
        lines += [
            "",
            "## Background Agents",
            "- None running at compaction time.",
        ]

    lines += [
        "",
        "---",
        "_This file is consumed by the SessionStart hook after compaction._",
        "_Delete it once it has been read to avoid stale state._",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def update_memory_active_section(memory_dir: str, data: dict) -> None:
    """Patch the '## Active Session' section in MEMORY.md, creating it if absent."""
    memory_path = os.path.join(memory_dir, "MEMORY.md")
    if not os.path.exists(memory_path):
        return

    with open(memory_path, encoding="utf-8") as f:
        content = f.read()

    git = data["git"]
    pr = data.get("pr")
    ts = data["timestamp"]

    section_lines = [
        "## Active Session",
        f"- **Last compaction:** {ts}",
        f"- **Branch:** `{git['branch']}`",
        f"- **Git status:** {git['status']}",
    ]
    if pr:
        section_lines.append(
            f"- **Active PR:** #{pr['number']} — {pr['title']} ({pr['url']})"
        )
    section_lines.append("")  # trailing newline before next section

    new_section = "\n".join(section_lines)

    if "## Active Session" in content:
        # Replace existing section
        updated = re.sub(
            r"## Active Session\n.*?(?=\n## |\Z)",
            new_section,
            content,
            flags=re.DOTALL,
        )
    else:
        # Append before the trailing newline
        updated = content.rstrip("\n") + "\n\n" + new_section + "\n"

    with open(memory_path, "w", encoding="utf-8") as f:
        f.write(updated)


def main() -> None:
    try:
        hook_input = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        sys.exit(0)

    cwd = hook_input.get("cwd", os.getcwd())
    session_id = hook_input.get("session_id", "")
    transcript_path = hook_input.get("transcript_path", "")
    trigger = hook_input.get("trigger", "auto")

    mem_dir = memory_dir_for(cwd)
    git = capture_git_state(cwd)
    pr = capture_pr_context(cwd, git["branch"])
    agent_ids = extract_agent_ids(transcript_path) if transcript_path else []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    data = {
        "session_id": session_id,
        "timestamp": ts,
        "trigger": trigger,
        "git": git,
        "pr": pr,
        "agent_ids": agent_ids,
    }

    write_handoff(mem_dir, data)
    update_memory_active_section(mem_dir, data)


if __name__ == "__main__":
    main()
